shared: &shared
  adapter: mysql
  pool: 5
  min_messages: warning

development:
  database: clojuredocs_development
  <<: *shared

test:
  database: clojuredocs_test
  <<: *shared

production:
  database: clojuredocs_production
  <<: *shared
